let students = [
  [
    uuidv4(),
    "MD Anas",
    20,
    "Male",
    "STU-001",
    "BCA",
    "anas.raza@example.com",
    "9876543210",
    "Delhi",
    "Sultanpuri, New Delhi",
    "Active",
  ],
  [
    uuidv4(),
    "Aman Sharma",
    19,
    "Male",
    "STU-002",
    "B.Com",
    "aman.sharma@example.com",
    "9812345678",
    "Jaipur",
    "Vaishali Nagar, Jaipur",
    "Active",
  ],
  [
    uuidv4(),
    "Priya Verma",
    21,
    "Female",
    "STU-003",
    "B.Sc",
    "priya.verma@example.com",
    "9898765432",
    "Lucknow",
    "Aliganj, Lucknow",
    "Inactive",
  ],
  [
    uuidv4(),
    "Mohammed Faizan",
    22,
    "Male",
    "STU-004",
    "BA",
    "faizan@example.com",
    "9123456780",
    "Bhopal",
    "MP Nagar, Bhopal",
    "Active",
  ],
  [
    uuidv4(),
    "Neha Singh",
    20,
    "Female",
    "STU-005",
    "BBA",
    "neha.singh@example.com",
    "9988776655",
    "Kanpur",
    "Civil Lines, Kanpur",
    "Active",
  ],
  [
    uuidv4(),
    "Rohan Gupta",
    21,
    "Male",
    "STU-006",
    "B.Tech",
    "rohan.gupta@example.com",
    "9765432109",
    "Noida",
    "Sector 62, Noida",
    "Inactive",
  ],
  [
    uuidv4(),
    "Ayesha Khan",
    19,
    "Female",
    "STU-007",
    "BCA",
    "ayesha@example.com",
    "9871203456",
    "Hyderabad",
    "Charminar, Hyderabad",
    "Active",
  ],
  [
    uuidv4(),
    "Arjun Mehta",
    22,
    "Male",
    "STU-008",
    "MBA",
    "arjun.mehta@example.com",
    "9871112233",
    "Pune",
    "Shivaji Nagar, Pune",
    "Active",
  ],
  [
    uuidv4(),
    "Sana Parveen",
    20,
    "Female",
    "STU-009",
    "B.Sc",
    "sana@example.com",
    "9811112233",
    "Patna",
    "Kankarbagh, Patna",
    "Active",
  ],
  [
    uuidv4(),
    "Rahul Yadav",
    21,
    "Male",
    "STU-010",
    "B.Com",
    "rahul@example.com",
    "9877776655",
    "Indore",
    "Vijay Nagar, Indore",
    "Inactive",
  ],
];
